---
framework: mocha
preRun:
     command:
        - npm ci
        - npm run build
preMerge:
  pattern:
    - "./packages/**/*.spec.ts"
postMerge:
  pattern: 
    - "./packages/**/*.spec.ts"
postRun:
     command:
        - node --version
version: 1.0
